# Use average of the mean for each feature to get gaussian distribution for the autoencoder, which is what it learns best. This is a common practice to improve AE performance when features have different scales or distributions.

# -*- coding: utf-8 -*-
"""aqi_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vgk0Nahm4l10VtCNAuEZZCr41uMdHFoC
"""

import os
import time
import pickle
import warnings
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

warnings.filterwarnings("ignore")

zip_code_to_lat_long_map = {
        77002 : (29.75635, -95.36538),
        77003 : (29.74961, -95.34521),
        77004 : (29.72477, -95.36498),
        77005 : (29.71824, -95.42413),
        77006 : (29.74086, -95.39126),
        77007 : (29.77242, -95.41052),
        77008 : (29.79962, -95.41046),
        77009 : (29.79176, -95.36760),
        77010 : (29.75314, -95.35747),
        77011 : (29.74336, -95.30439),
        77012 : (29.70974, -95.28260),
        77013 : (29.78747, -95.21996),
        77014 : (29.98213, -95.46244),
        77015 : (29.78669, -95.18601),
        77016 : (29.85719, -95.30002),
        77017 : (29.68472, -95.25424),
        77018 : (29.82655, -95.42663),
        77019 : (29.75290, -95.41066),
        77020 : (29.77553, -95.30136),
        77021 : (29.69757, -95.35047),
        77022 : (29.82863, -95.37664),
        77023 : (29.72466, -95.31802),
        77024 : (29.76715, -95.50563),
        77025 : (29.68894, -95.43402),
        77026 : (29.79951, -95.32671),
        77027 : (29.73995, -95.44335),
        77028 : (29.82713, -95.26845),
        77029 : (29.76330, -95.26177),
        77030 : (29.70597, -95.40253),
        77031 : (29.65221, -95.54623),
        77032 : (29.93835, -95.34247),
        77033 : (29.66757, -95.34163),
        77034 : (29.63464, -95.21764),
        77035 : (29.65269, -95.47688),
        77036 : (29.70041, -95.53820),
        77037 : (29.90046, -95.40978),
        77038 : (29.91565, -95.44023),
        77039 : (29.90221, -95.33851),
        77040 : (29.88052, -95.52274),
        77041 : (29.87938, -95.58588),
        77042 : (29.74046, -95.55901),
        77043 : (29.80865, -95.56048),
        77044 : (29.87541, -95.19709),
        77045 : (29.63319, -95.42477),
        77046 : (29.73386, -95.43165),
        77047 : (29.62741, -95.38158),
        77048 : (29.62974, -95.32549),
        77049 : (29.81149, -95.15944),
        77050 : (29.88912, -95.26770),
        77051 : (29.65846, -95.36788),
        77053 : (29.59165, -95.46011),
        77054 : (29.68268, -95.40384),
        77055 : (29.79688, -95.49566),
        77056 : (29.74178, -95.46843),
        77057 : (29.73815, -95.48502),
        77058 : (29.56167, -95.09252),
        77059 : (29.59887, -95.11537),
        77060 : (29.93526, -95.39834),
        77061 : (29.65566, -95.27889),
        77062 : (29.57642, -95.13786),
        77063 : (29.73726, -95.52314),
        77064 : (29.91453, -95.55649),
        77065 : (29.92915, -95.61607),
        77066 : (29.95952, -95.50134),
        77067 : (29.95349, -95.45072),
        77068 : (30.00302, -95.47963),
        77069 : (29.98619, -95.52312),
        77070 : (29.97831, -95.57229),
        77071 : (29.65257, -95.52063),
        77072 : (29.70052, -95.58442),
        77073 : (29.99616, -95.40651),
        77074 : (29.69144, -95.51573),
        77075 : (29.62059, -95.26134),
        77076 : (29.85739, -95.38343),
        77077 : (29.74721, -95.62213),
        77078 : (29.85337, -95.26289),
        77079 : (29.77594, -95.60134),
        77080 : (29.81544, -95.52211),
        77081 : (29.71406, -95.48079),
        77082 : (29.72843, -95.63738),
        77083 : (29.69422, -95.64367),
        77084 : (29.82749, -95.65992),
        77085 : (29.62442, -95.48803),
        77086 : (29.92852, -95.49576),
        77087 : (29.68441, -95.30458),
        77088 : (29.88062, -95.45274),
        77089 : (29.58792, -95.22088),
        77090 : (30.01713, -95.44653),
        77091 : (29.85360, -95.44288),
        77092 : (29.83169, -95.47378),
        77093 : (29.86102, -95.34198),
        77094 : (29.77058, -95.69305),
        77095 : (29.90132, -95.64813),
        77096 : (29.67464, -95.47965),
        77098 : (29.73542, -95.41791),
        77099 : (29.67879, -95.58541),
        77204 : (29.72090, -95.36778)
        }

print(len(zip_code_to_lat_long_map))

# ============================================================
# Config
# ============================================================

@dataclass
class Config:
    air_data_path: str = "/content/week3_air_quality_hourly_20260305_145306.csv"
    weather_data_path: str = "/content/week3_weather_hourly_20260305_145306.csv"
    target_col: str = "us_aqi"

    # Split/scaling choices
    test_size: float = 0.20
    val_size: float = 0.10
    train_size: float = 0.70
    random_state: int = 10

    # Sequence settings for LSTM
    lookback: int = 24 # The number of previous sequences to "lookback" on
    horizon: int = 1 # The number of hour(s) to predict ahead

    # AE settings
    latent_dim: int = 22
    ae_hidden_dims: List[int] = field(default_factory=list)  # single bottleneck layer only
    ae_epochs: int = 100
    ae_lr: float = 1e-3

    # LSTM settings
    lstm_hidden: int = 512
    lstm_layers: int = 3
    lstm_dropout: float = 1e-3
    lstm_epochs: int = 100
    lstm_lr: float = .0007
    patience: int = 20
    batch_size: int = 256

    seed: int = 42
    show_plots: bool = True
    save_dir: str = "saved_models_aiq_training_cam"

    # Exact drop pattern from notebook feature selection
    cols_to_drop: List[str] = field(default_factory=lambda: [
        "city", "state", "time", "us_aqi",
        "hour", "day_of_week", "month", "day",
    ])

    @property
    def device(self) -> torch.device:
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def seed_everything(seed: int):
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

# ============================================================
# Models
# ============================================================

class AQI_LSTM(nn.Module):
    def __init__(self, input_dim: int, hidden_size: int = 64,
                 num_layers: int = 1, dropout: float = 0.0):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_dim,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])


class ShallowAutoencoder(nn.Module):
    """
    Matches the notebook's '1 hidden layer, 22 neurons' setup:
        input -> 22 -> input

    The 22-unit layer is both the hidden layer and latent representation.
    """

    def __init__(self, input_dim: int, latent_dim: int = 22):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, latent_dim),
            nn.ReLU(),
        )
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, input_dim),
            nn.Sigmoid(),
        )

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        z = self.encoder(x)
        recon = self.decoder(z)
        return recon, z

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.encoder(x)

# ============================================================
# Data pipeline
# ============================================================

class AIQTrainingPipeline:
    """Prepare aiq_training_cam using the notebook's feature/scaling logic."""

    def __init__(self, cfg: Config):
        self.cfg = cfg
        self.feature_cols: List[str] = []
        self.ae_scaler = MinMaxScaler() # Use MinMaxScaler for autoencoder, StandardScaler for LSTM sequences (after AE transformation)
        self.lstm_scaler = StandardScaler()


        self.train_df = None
        self.test_df = None

        self.X_train = self.X_val = self.X_test = None
        self.y_train = self.y_val = self.y_test = None

        self.X_train_seq = self.X_val_seq = self.X_test_seq = None
        self.y_train_seq = self.y_val_seq = self.y_test_seq = None


    def prepare(self) -> "AIQTrainingPipeline":
        air_weather_df = self._load_and_engineer()
        self.train_df, self.val_df, self.test_df = self._split_scale(air_weather_df)

        # row-level arrays for AE
        self.X_train = self.train_df[self.feature_cols].values.astype(np.float32)
        self.X_val = self.val_df[self.feature_cols].values.astype(np.float32)
        self.X_test = self.test_df[self.feature_cols].values.astype(np.float32)
        
        self.y_train = self.train_df[self.cfg.target_col].values.reshape(-1, 1).astype(np.float32)
        self.y_val = self.val_df[self.cfg.target_col].values.reshape(-1, 1).astype(np.float32)
        self.y_test = self.test_df[self.cfg.target_col].values.reshape(-1, 1).astype(np.float32)

        # grouped sequences for LSTM
        self.X_train_seq, self.y_train_seq = self.make_sequences(self.train_df)
        self.X_val_seq, self.y_val_seq = self.make_sequences(self.val_df)
        self.X_test_seq, self.y_test_seq = self.make_sequences(self.test_df)

        print(f"Train rows: {self.train_df.shape}, Test rows: {self.test_df.shape}")
        print(f"Train seq: {self.X_train_seq.shape}, Test seq: {self.X_test_seq.shape}")
        return self

    def _load_and_engineer(self) -> pd.DataFrame:
        air_df = pd.read_csv(self.cfg.air_data_path)
        weather_df = pd.read_csv(self.cfg.weather_data_path)
        air_weather_df = pd.merge(
            air_df, weather_df, on=["time", "zip", "city", "state"], how="inner"
        )

        coords = air_weather_df["zip"].map(zip_code_to_lat_long_map)
        air_weather_df["latitude"] = coords.str[0]
        air_weather_df["longitude"] = coords.str[1]

        air_weather_df["time"] = pd.to_datetime(air_weather_df["time"], utc=True)
        air_weather_df = air_weather_df.sort_values(["zip", "time"]).reset_index(drop=True)

        air_weather_df["hour_sin"] = np.sin(2 * np.pi * air_weather_df["time"].dt.hour / 24)
        air_weather_df["hour_cos"] = np.cos(2 * np.pi * air_weather_df["time"].dt.hour / 24)
        air_weather_df["day_of_week_sin"] = np.sin(2 * np.pi * air_weather_df["time"].dt.dayofweek / 7)
        air_weather_df["day_of_week_cos"] = np.cos(2 * np.pi * air_weather_df["time"].dt.dayofweek / 7)
        air_weather_df["month_sin"] = np.sin(2 * np.pi * air_weather_df["time"].dt.month / 12)
        air_weather_df["month_cos"] = np.cos(2 * np.pi * air_weather_df["time"].dt.month / 12)

        air_weather_df["hour"] = air_weather_df["time"].dt.hour
        air_weather_df["day_of_week"] = air_weather_df["time"].dt.dayofweek
        air_weather_df["is_weekend"] = air_weather_df["day_of_week"].isin([5, 6]).astype(int)
        air_weather_df["month"] = air_weather_df["time"].dt.month
        air_weather_df["day"] = air_weather_df["time"].dt.day

        # IMPORTANT: do NOT drop zip yet
        x = air_weather_df.drop(columns=self.cfg.cols_to_drop)

        # zip stays only for grouping, not as a model feature
        self.feature_cols = [c for c in x.columns if c != "zip"]
        self._df = air_weather_df

        print(f"Loaded: {air_weather_df.shape}")
        print(f"Target: {self.cfg.target_col}")
        print(f"Features ({len(self.feature_cols)}): {self.feature_cols}")
        return air_weather_df

    def _split_scale(self, air_weather_df: pd.DataFrame):
        train_parts = []
        test_parts = []
        val_parts = []

        for zip_code, group in air_weather_df.groupby("zip"):
            group = group.sort_values("time").reset_index(drop=True)
            split_idx_train = int(len(group) * self.cfg.train_size)
            split_idx_val = int(len(group) * (1 - self.cfg.val_size))
            split_idx_test = int(len(group) * (1 - self.cfg.test_size))

            train_parts.append(group.iloc[:split_idx_train].copy())
            val_parts.append(group.iloc[split_idx_train:split_idx_val].copy())
            test_parts.append(group.iloc[split_idx_val:split_idx_test].copy())

        train_df = pd.concat(train_parts, axis=0).reset_index(drop=True)
        val_df = pd.concat(val_parts, axis=0).reset_index(drop=True)
        test_df = pd.concat(test_parts, axis=0).reset_index(drop=True)

        train_df[self.feature_cols] = self.ae_scaler.fit_transform(
            train_df[self.feature_cols].astype(np.float32)
        )
        val_df[self.feature_cols] = self.ae_scaler.transform(
            val_df[self.feature_cols].astype(np.float32)
        )
        test_df[self.feature_cols] = self.ae_scaler.transform(
            test_df[self.feature_cols].astype(np.float32)
        )

        train_df[self.feature_cols] = np.nan_to_num(
            train_df[self.feature_cols], nan=0.0, posinf=0.0, neginf=0.0
        )
        val_df[self.feature_cols] = np.nan_to_num(
            val_df[self.feature_cols], nan=0.0, posinf=0.0, neginf=0.0
        )
        test_df[self.feature_cols] = np.nan_to_num(
            test_df[self.feature_cols], nan=0.0, posinf=0.0, neginf=0.0
        )

        return train_df, val_df, test_df

    @property
    def input_dim(self) -> int:
        return len(self.feature_cols) + 1

    def make_sequences(self, df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
        lookback, horizon = self.cfg.lookback, self.cfg.horizon
        Xs, ys = [], []

        for zip_code, group in df.groupby("zip"):
            group = group.sort_values("time").reset_index(drop=True)

            X = group[self.feature_cols].values.astype(np.float32)
            y = group[self.cfg.target_col].values.astype(np.float32)

            if len(group) < lookback + horizon:
                continue

            for i in range(lookback, len(group) - horizon + 1):
              past_features = X[i-lookback:i]
              past_aqi = y[i-lookback:i].reshape(lookback, 1)

              seq = np.concatenate([past_features, past_aqi], axis=1)

              Xs.append(seq)
              ys.append(y[i + horizon - 1])

        return np.array(Xs, dtype=np.float32), np.array(ys, dtype=np.float32)

# ============================================================
# AE reducer
# ============================================================

class AEReducer:
    def __init__(self, cfg: Config, input_dim: int):
        self.cfg = cfg
        self.model = ShallowAutoencoder(input_dim=input_dim, latent_dim=cfg.latent_dim)
        self.train_history: List[float] = []

    def fit(self, X_train: np.ndarray):
        loader = DataLoader(
            TensorDataset(torch.tensor(X_train, dtype=torch.float32)),
            batch_size=self.cfg.batch_size,
            shuffle=True,
            drop_last=False,
        )

        criterion = nn.MSELoss()
        optimizer = optim.Adam(self.model.parameters(), lr=self.cfg.ae_lr, weight_decay=1e-5)
        self.model.to(self.cfg.device).train()
        self.train_history = []

        for epoch in range(self.cfg.ae_epochs):
            total = 0.0
            t0 = time.time()
            for (batch,) in loader:
                batch = batch.to(self.cfg.device)
                optimizer.zero_grad()
                recon, _ = self.model(batch)
                loss = criterion(recon, batch)
                loss.backward()
                optimizer.step()
                total += loss.item()

            avg = total / len(loader)
            self.train_history.append(avg)
            if (epoch + 1) % 10 == 0 or epoch == 0:
                print(f"    [AE] Epoch {epoch+1:3d}/{self.cfg.ae_epochs}  loss={avg:.6f}  ({time.time()-t0:.1f}s)")

    def transform(self, X: np.ndarray) -> np.ndarray:
        self.model.eval()
        with torch.no_grad():
            X_t = torch.tensor(X, dtype=torch.float32).to(self.cfg.device)
            z = self.model.encode(X_t)
        return z.cpu().numpy()

    def fit_transform(self, X_train: np.ndarray) -> np.ndarray:
        self.fit(X_train)
        return self.transform(X_train)

# ============================================================
# LSTM trainer
# ============================================================

class EarlyStopping:
    def __init__(self, patience: int = 10):
        self.patience = patience
        self.counter = 0
        self.best_loss = float("inf")
        self.best_state = None

    def step(self, model: nn.Module, val_loss: float) -> bool:
        if val_loss < self.best_loss:
            self.best_loss = val_loss
            self.best_state = {k: v.clone() for k, v in model.state_dict().items()}
            self.counter = 0
            return False
        else:
            self.counter += 1
            return self.counter >= self.patience
        
class LSTMTrainer:
    def __init__(self, cfg: Config):
        self.cfg = cfg

    def _loader(self, X, y, shuffle: bool):
        return DataLoader(
            TensorDataset(
                torch.tensor(X, dtype=torch.float32),
                torch.tensor(y, dtype=torch.float32).unsqueeze(1),
            ),
            batch_size=self.cfg.batch_size,
            shuffle=shuffle,
        )

    def train(self, model, X_train, y_train, X_val, y_val, name="LSTM"):
        train_dl = self._loader(X_train, y_train, True)
        val_dl = self._loader(X_val, y_val, False)

        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=self.cfg.lstm_lr, weight_decay=1e-5)
        model.to(self.cfg.device)
        earlystopper = EarlyStopping(patience=self.cfg.patience)

        train_hist, val_hist = [], []

        for ep in range(self.cfg.lstm_epochs):
            model.train()

            train_loss = 0.0
            for xb, yb in train_dl:
                xb, yb = xb.to(self.cfg.device), yb.to(self.cfg.device)

                pred = model(xb) # forward pass

                optimizer.zero_grad()
                loss = criterion(pred, yb)
                loss.backward()

                nn.utils.clip_grad_norm_(model.parameters(), 1.0) # Clip gradients that exceed norm of 1.0, which is [gradient * (1 / L2 norm of gradients)]
                optimizer.step()
                train_loss += loss.item()
            train_loss /= len(train_dl)

            model.eval()
            val_loss = 0.0
            with torch.no_grad():
                for xb, yb in val_dl:
                    xb, yb = xb.to(self.cfg.device), yb.to(self.cfg.device)
                    val_loss += criterion(model(xb), yb).item()
            val_loss /= len(val_dl)

            train_hist.append(train_loss)
            val_hist.append(val_loss)

            if (ep + 1) % 5 == 0 or ep == 0:
                print(f"    [{name}] Epoch {ep+1:3d}/{self.cfg.lstm_epochs}  train={train_loss:.6f}  test={val_loss:.6f}")

            if(earlystopper.step(model, val_loss)):
                print(f"    [{name}] Early stopping at epoch {ep+1}")
                break

        if earlystopper.best_state is not None:
            model.load_state_dict(earlystopper.best_state)
        return train_hist, val_hist

    @torch.no_grad()
    def predict(self, model, X):
        model.eval().to(self.cfg.device)
        preds = []
        for i in range(0, len(X), self.cfg.batch_size):
            batch = torch.tensor(X[i:i+self.cfg.batch_size], dtype=torch.float32).to(self.cfg.device)
            preds.append(model(batch).cpu().numpy())
        return np.concatenate(preds).flatten()

    def evaluate(self, y_true, y_pred, label=""):
        yt = y_true.reshape(-1) # ensure 1D for metric calculations
        yp = y_pred.reshape(-1)

        rmse = float(np.sqrt(mean_squared_error(yt, yp)))
        mae = float(mean_absolute_error(yt, yp))
        r2 = float(1 - np.sum((yt - yp) ** 2) / (np.sum((yt - yt.mean()) ** 2) + 1e-10))
        print(f"    [{label}] RMSE={rmse:.4f}  MAE={mae:.4f}  R²={r2:.4f}")
        return {"label": label, "rmse": rmse, "mae": mae, "r2": r2, "y_true": yt, "y_pred": yp}

# ============================================================
# Save helpers
# ============================================================

def save_artifacts(save_dir: str, model: AQI_LSTM, ae_reducer: AEReducer,
                   pipeline: AIQTrainingPipeline, cfg: Config, metrics: Dict,
                   loss_curves: Tuple[List[float], List[float]],
                   lstm_input_dim: int):
    os.makedirs(save_dir, exist_ok=True)

    torch.save({
        "model_state_dict": model.state_dict(),
        "config": {
            "input_dim": lstm_input_dim,
            "hidden_size": cfg.lstm_hidden,
            "num_layers": cfg.lstm_layers,
            "lookback": cfg.lookback,
            "latent_dim": cfg.latent_dim,
            "feature_cols": pipeline.feature_cols,
            "target_col": cfg.target_col,
        },
        "metrics": metrics,
        "train_loss": loss_curves[0],
        "test_loss": loss_curves[1],
    }, os.path.join(save_dir, "lstm_ae22.pt"))

    torch.save(ae_reducer.model.state_dict(), os.path.join(save_dir, "ae_22.pt"))

    with open(os.path.join(save_dir, "scalers.pkl"), "wb") as f:
        pickle.dump({
            "ae_scaler": pipeline.ae_scaler,
            "lstm_scaler" : pipeline.lstm_scaler
        }, f)

    pd.DataFrame([{
        "Model": metrics["label"],
        "RMSE": metrics["rmse"],
        "MAE": metrics["mae"],
        "R2": metrics["r2"],
    }]).to_csv(os.path.join(save_dir, "results_summary.csv"), index=False)

# ============================================================
# Run
# ============================================================

def run(cfg: Config):
    seed_everything(cfg.seed)
    print(f"Device: {cfg.device}\n")

    print("=" * 60)
    print("  DATA PIPELINE")
    print("=" * 60)
    pipeline = AIQTrainingPipeline(cfg).prepare()

    print("\n" + "=" * 60)
    print("  TRAIN SHALLOW AUTOENCODER")
    print("=" * 60)
    ae = AEReducer(cfg, input_dim=pipeline.X_train.shape[1]) #subtract one because, autoencoder will not encode the added lag input
    X_train_latent = ae.fit_transform(pipeline.X_train)
    X_val_latent = ae.transform(pipeline.X_val)
    X_test_latent = ae.transform(pipeline.X_test)

    # X_train_latent = pipeline.lstm_scaler.fit_transform(X_train_latent) # Scale the latent features for LSTM training using StandardScaler
    # X_val_latent = pipeline.lstm_scaler.transform(X_val_latent)
    # X_test_latent = pipeline.lstm_scaler.transform(X_test_latent)

    latent_cols = [f"z{i}" for i in range(cfg.latent_dim)] # latent_dim is 22, so this will create z0, z1, ..., z21

    train_latent_df = pipeline.train_df[["zip", "time", cfg.target_col]].copy() # Get the original train_df structure with zip, time, and target_col
    val_latent_df = pipeline.val_df[["zip", "time", cfg.target_col]].copy()
    test_latent_df = pipeline.test_df[["zip", "time", cfg.target_col]].copy()

    train_latent_df[latent_cols] = X_train_latent # Add the latent features to the train dataframe
    val_latent_df[latent_cols] = X_val_latent
    test_latent_df[latent_cols] = X_test_latent

    original_feature_cols = pipeline.feature_cols.copy() # Save original feature columns to restore later
    pipeline.feature_cols = latent_cols 

    try:
        X_train_seq, y_train_seq = pipeline.make_sequences(train_latent_df) # Generate sequences using the latent features
        X_val_seq, y_val_seq = pipeline.make_sequences(val_latent_df)
        X_test_seq, y_test_seq = pipeline.make_sequences(test_latent_df)
    finally:
        pipeline.feature_cols = original_feature_cols

    #X_train_seq.shape is (num_samples, lookback, num_features + 1) where num_features is the number of latent features (22) and the +1 is for the lagged target variable included in the sequence

    print(f"Latent train seq: {X_train_seq.shape}")
    print(f"Latent test  seq: {X_test_seq.shape}")

    print("\n" + "=" * 60)
    print("  TRAIN LSTM")
    print("=" * 60)
    model = AQI_LSTM(
        input_dim=X_train_seq.shape[2],
        hidden_size=cfg.lstm_hidden,
        num_layers=cfg.lstm_layers,
        dropout=cfg.lstm_dropout,
    )
    trainer = LSTMTrainer(cfg)
    loss_curves = trainer.train(
        model,
        X_train_seq,
        y_train_seq,
        X_val_seq,
        y_val_seq,
        name="LSTM+AE22"
    )

    print("\n" + "=" * 60)
    print("  EVALUATION")
    print("=" * 60)
    preds = trainer.predict(model, X_test_seq)
    metrics = trainer.evaluate(y_test_seq, preds, label="LSTM+AE22")

    save_artifacts(cfg.save_dir, model, ae, pipeline, cfg, metrics, loss_curves, X_train_seq.shape[2])

    return {
        "pipeline": pipeline,
        "ae": ae,
        "model": model,
        "metrics": metrics,
        "loss_curves": loss_curves,
        "X_train_seq": X_train_seq,
        "y_train_seq": y_train_seq,
        "X_val_seq": X_val_seq,
        "y_val_seq": y_val_seq,
    }


if __name__ == "__main__":
    cfg = Config()
    results = run(cfg)

# # ============================================================
# # VALIDATION: Load saved artifacts
# # ============================================================

# cfg = Config()
# seed_everything(cfg.seed)
# device = cfg.device
# print(f"Device: {device}")

# SAVE_DIR = cfg.save_dir

# # --- Load LSTM checkpoint ---
# # PyTorch 2.6+ defaults to weights_only=True; we need full checkpoint metadata here.
# try:
#     lstm_ckpt = torch.load(
#         os.path.join(SAVE_DIR, "lstm_ae22.pt"),
#         map_location=device,
#         weights_only=False,
#     )
# except (pickle.UnpicklingError, RuntimeError):
#     import numpy as np
#     with torch.serialization.safe_globals([np._core.multiarray._reconstruct]):
#         lstm_ckpt = torch.load(
#             os.path.join(SAVE_DIR, "lstm_ae22.pt"),
#             map_location=device,
#             weights_only=False,
#         )

# lstm_cfg_saved = lstm_ckpt["config"]
# feature_cols_saved = lstm_cfg_saved["feature_cols"]

# lstm_model = AQI_LSTM(
#     input_dim=lstm_cfg_saved["input_dim"],
#     hidden_size=lstm_cfg_saved["hidden_size"],
#     num_layers=lstm_cfg_saved["num_layers"],
# ).to(device)
# lstm_model.load_state_dict(lstm_ckpt["model_state_dict"])
# lstm_model.eval()
# print("LSTM loaded.")

# # --- Load AE weights ---
# ae_model = ShallowAutoencoder(input_dim=len(feature_cols_saved), latent_dim=cfg.latent_dim).to(device)
# ae_model.load_state_dict(torch.load(os.path.join(SAVE_DIR, "ae_22.pt"), map_location=device))
# ae_model.eval()
# print("Autoencoder loaded.")

# # --- Load scaler ---
# with open(os.path.join(SAVE_DIR, "scalers.pkl"), "rb") as f:
#     scalers = pickle.load(f)
# ae_scaler: MinMaxScaler = scalers["ae_scaler"]
# print("Scaler loaded.")

# # --- Saved training metrics (for comparison) ---
# train_metrics_saved = lstm_ckpt["metrics"]
# print(f"\nTraining-set metrics (from saved checkpoint):")
# print(f"  RMSE={train_metrics_saved['rmse']:.4f}  MAE={train_metrics_saved['mae']:.4f}  R²={train_metrics_saved['r2']:.4f}")

# # ============================================================
# # TRAINING PERFORMANCE PLOTS
# # All data comes from the saved checkpoint — no retraining.
# # ============================================================

# train_loss  = lstm_ckpt["train_loss"]   # list of per-epoch train MSE
# test_loss   = lstm_ckpt["test_loss"]    # list of per-epoch val  MSE
# epochs_ran  = list(range(1, len(train_loss) + 1))

# # Saved test-split predictions (y_true / y_pred stored in metrics dict)
# ts_true = train_metrics_saved["y_true"]   # original held-out test split
# ts_pred = train_metrics_saved["y_pred"]
# ts_err  = ts_true - ts_pred


# # ── helper: AQI category bins ────────────────────────────────────────────────
# AQI_BINS   = [0, 50, 100, 150, 200, 300, 500]
# AQI_LABELS = ["Good", "Moderate", "USG", "Unhealthy", "Very Unhealthy", "Hazardous"]
# AQI_COLORS = ["#00e400", "#ffff00", "#ff7e00", "#ff0000", "#99004c", "#7e0023"]

# def aqi_category(values):
#     return pd.cut(values, bins=AQI_BINS, labels=AQI_LABELS, right=True)


# # ════════════════════════════════════════════════════════════════
# # FIGURE 1 — Loss curves (LSTM train vs val MSE)
# # ════════════════════════════════════════════════════════════════
# fig, axes = plt.subplots(1, 2, figsize=(13, 4))
# fig.suptitle("LSTM Training Loss Curves", fontsize=13, fontweight="bold")

# ax = axes[0]
# ax.plot(epochs_ran, train_loss, label="Train MSE", color="steelblue", linewidth=2)
# ax.plot(epochs_ran, test_loss,  label="Val MSE",   color="darkorange", linewidth=2, linestyle="--")
# best_ep = int(np.argmin(test_loss)) + 1
# ax.axvline(best_ep, color="red", linestyle=":", linewidth=1.5, label=f"Best epoch={best_ep}")
# ax.set_title("MSE per Epoch (raw)")
# ax.set_xlabel("Epoch")
# ax.set_ylabel("MSE Loss")
# ax.legend()
# ax.grid(True, alpha=0.3)

# ax = axes[1]
# ax.plot(epochs_ran, np.sqrt(train_loss), label="Train RMSE", color="steelblue", linewidth=2)
# ax.plot(epochs_ran, np.sqrt(test_loss),  label="Val RMSE",   color="darkorange", linewidth=2, linestyle="--")
# ax.axvline(best_ep, color="red", linestyle=":", linewidth=1.5, label=f"Best epoch={best_ep}")
# ax.set_title("RMSE per Epoch")
# ax.set_xlabel("Epoch")
# ax.set_ylabel("RMSE")
# ax.legend()
# ax.grid(True, alpha=0.3)

# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_loss_curves.png"), dpi=150, bbox_inches="tight")
# plt.show()


# # ════════════════════════════════════════════════════════════════
# # FIGURE 2 — Train/Val gap & overfitting indicator
# # ════════════════════════════════════════════════════════════════
# gap = np.array(test_loss) - np.array(train_loss)

# fig, ax = plt.subplots(figsize=(9, 4))
# ax.fill_between(epochs_ran, gap, 0,
#                 where=(gap > 0), alpha=0.35, color="tomato",   label="Val > Train (overfit zone)")
# ax.fill_between(epochs_ran, gap, 0,
#                 where=(gap <= 0), alpha=0.35, color="steelblue", label="Train > Val (underfit zone)")
# ax.plot(epochs_ran, gap, color="black", linewidth=1.5)
# ax.axhline(0, color="gray", linewidth=0.8, linestyle="--")
# ax.set_title("Train-Val Loss Gap per Epoch (positive = overfitting)")
# ax.set_xlabel("Epoch")
# ax.set_ylabel("Val MSE − Train MSE")
# ax.legend()
# ax.grid(True, alpha=0.3)
# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_val_gap.png"), dpi=150, bbox_inches="tight")
# plt.show()


# # ════════════════════════════════════════════════════════════════
# # FIGURE 3 — LSTM weight & bias norms (per layer)
# # ════════════════════════════════════════════════════════════════
# param_names, param_norms = [], []
# for name, param in lstm_model.named_parameters():
#     param_names.append(name)
#     param_norms.append(param.data.norm().item())

# fig, ax = plt.subplots(figsize=(9, 4))
# colors_bar = ["steelblue" if "weight" in n else "darkorange" for n in param_names]
# bars = ax.barh(param_names, param_norms, color=colors_bar, alpha=0.85)
# for bar, val in zip(bars, param_norms):
#     ax.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height()/2,
#             f"{val:.4f}", va="center", fontsize=8)
# ax.set_title("LSTM Parameter L2 Norms (trained weights)")
# ax.set_xlabel("L2 Norm")
# from matplotlib.patches import Patch
# ax.legend(handles=[
#     Patch(color="steelblue",  label="Weight matrices"),
#     Patch(color="darkorange", label="Bias vectors"),
# ])
# ax.grid(True, alpha=0.3, axis="x")
# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_weight_norms.png"), dpi=150, bbox_inches="tight")
# plt.show()


# # ════════════════════════════════════════════════════════════════
# # FIGURE 4 — AE reconstruction quality on training features
# # (sample a few feature channels; lower = better compression)
# # ════════════════════════════════════════════════════════════════
# # Re-encode a random batch through the full AE (encoder + decoder)
# N_SAMPLE = 512
# rng = np.random.default_rng(42)
# sample_idx = rng.integers(0, 10000, size=N_SAMPLE)

# # We reconstruct from the scaler's feature range — use a uniform grid as proxy
# dummy_input = torch.zeros(N_SAMPLE, len(feature_cols_saved), dtype=torch.float32).to(device)
# dummy_input = torch.rand(N_SAMPLE, len(feature_cols_saved), dtype=torch.float32).to(device)
# with torch.no_grad():
#     recon, _ = ae_model(dummy_input)
# recon_err = (dummy_input - recon).abs().cpu().numpy()   # (N, 30)
# mean_err_per_feat = recon_err.mean(axis=0)

# fig, axes = plt.subplots(1, 2, figsize=(14, 5))
# fig.suptitle("Autoencoder Reconstruction Quality", fontsize=13, fontweight="bold")

# ax = axes[0]
# ax.bar(range(len(feature_cols_saved)), mean_err_per_feat, color="steelblue", alpha=0.85)
# ax.set_xticks(range(len(feature_cols_saved)))
# ax.set_xticklabels(feature_cols_saved, rotation=90, fontsize=7)
# ax.set_title("Mean Absolute Reconstruction Error per Feature")
# ax.set_ylabel("MAE (scaled space)")
# ax.grid(True, alpha=0.3, axis="y")

# ax = axes[1]
# # Overall reconstruction error distribution
# ax.hist(recon_err.flatten(), bins=60, color="steelblue", edgecolor="white", alpha=0.85)
# ax.set_title("Distribution of AE Reconstruction Errors (all features)")
# ax.set_xlabel("Absolute error (scaled)")
# ax.set_ylabel("Count")
# ax.grid(True, alpha=0.3)

# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_ae_reconstruction.png"), dpi=150, bbox_inches="tight")
# plt.show()


# # ════════════════════════════════════════════════════════════════
# # FIGURE 5 — Original test-split: Actual vs Predicted
# # ════════════════════════════════════════════════════════════════
# fig, axes = plt.subplots(1, 2, figsize=(14, 5))
# fig.suptitle("Original Test-Split Performance (Training Notebook)", fontsize=13, fontweight="bold")

# ax = axes[0]
# ax.plot(ts_true[:400],  label="Actual",    color="steelblue",  linewidth=1)
# ax.plot(ts_pred[:400],  label="Predicted", color="darkorange", linewidth=1, linestyle="--")
# ax.set_title("Actual vs Predicted AQI — Test Split (first 400)")
# ax.set_xlabel("Sample index")
# ax.set_ylabel("AQI")
# ax.legend()
# ax.grid(True, alpha=0.3)

# ax = axes[1]
# ax.scatter(ts_true, ts_pred, alpha=0.25, s=6, color="steelblue")
# lims = [min(ts_true.min(), ts_pred.min()), max(ts_true.max(), ts_pred.max())]
# ax.plot(lims, lims, "r--", linewidth=1.5, label="Perfect")
# ax.set_title(f"Scatter: Test Split\nRMSE={train_metrics_saved['rmse']:.4f}  R²={train_metrics_saved['r2']:.4f}")
# ax.set_xlabel("Actual AQI")
# ax.set_ylabel("Predicted AQI")
# ax.legend()
# ax.grid(True, alpha=0.3)

# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_test_split_predictions.png"), dpi=150, bbox_inches="tight")
# plt.show()


# # ════════════════════════════════════════════════════════════════
# # FIGURE 6 — AQI distribution: test-split actual vs predicted
# # ════════════════════════════════════════════════════════════════
# fig, axes = plt.subplots(1, 2, figsize=(14, 5))
# fig.suptitle("AQI Value Distributions — Test Split", fontsize=13, fontweight="bold")

# ax = axes[0]
# ax.hist(ts_true, bins=60, alpha=0.7, color="steelblue",  label="Actual",    density=True)
# ax.hist(ts_pred, bins=60, alpha=0.7, color="darkorange", label="Predicted", density=True)
# ax.set_title("Density: Actual vs Predicted AQI")
# ax.set_xlabel("AQI")
# ax.set_ylabel("Density")
# ax.legend()
# ax.grid(True, alpha=0.3)

# ax = axes[1]
# # Category-level error boxplot
# cats = aqi_category(pd.Series(ts_true))
# cat_errors = {}
# for cat in AQI_LABELS:
#     mask = (cats == cat)
#     if mask.sum() > 0:
#         cat_errors[cat] = ts_err[mask.values]

# present_cats = list(cat_errors.keys())
# bp = ax.boxplot([cat_errors[c] for c in present_cats],
#                 labels=present_cats, patch_artist=True, notch=False)
# cat_color_map = dict(zip(AQI_LABELS, AQI_COLORS))
# for patch, cat in zip(bp["boxes"], present_cats):
#     patch.set_facecolor(cat_color_map[cat])
#     patch.set_alpha(0.7)
# ax.axhline(0, color="red", linestyle="--", linewidth=1)
# ax.set_title("Residual Distribution by AQI Category")
# ax.set_xlabel("AQI Category")
# ax.set_ylabel("Residual (Actual − Predicted)")
# ax.tick_params(axis="x", rotation=20)
# ax.grid(True, alpha=0.3, axis="y")

# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_aqi_distributions.png"), dpi=150, bbox_inches="tight")
# plt.show()


# # ════════════════════════════════════════════════════════════════
# # FIGURE 7 — Absolute error vs AQI magnitude (test split)
# # ════════════════════════════════════════════════════════════════
# abs_err = np.abs(ts_err)

# fig, axes = plt.subplots(1, 2, figsize=(14, 5))
# fig.suptitle("Error Magnitude Analysis — Test Split", fontsize=13, fontweight="bold")

# ax = axes[0]
# ax.scatter(ts_true, abs_err, alpha=0.2, s=5, color="steelblue")
# # rolling mean of abs error
# sorted_idx = np.argsort(ts_true)
# x_sorted = ts_true[sorted_idx]
# e_sorted  = abs_err[sorted_idx]
# window = max(1, len(x_sorted) // 60)
# rolling_mean = np.convolve(e_sorted, np.ones(window)/window, mode="valid")
# x_rolling = x_sorted[window//2: window//2 + len(rolling_mean)]
# ax.plot(x_rolling, rolling_mean, color="red", linewidth=2, label="Rolling mean AE")
# ax.set_title("Absolute Error vs AQI Value")
# ax.set_xlabel("Actual AQI")
# ax.set_ylabel("|Residual|")
# ax.legend()
# ax.grid(True, alpha=0.3)

# ax = axes[1]
# # Cumulative percentage of predictions within ±N AQI units
# thresholds = np.arange(0, 51, 1)
# pct_within = [(abs_err <= t).mean() * 100 for t in thresholds]
# ax.plot(thresholds, pct_within, color="steelblue", linewidth=2)
# for thr, color in [(5, "green"), (10, "orange"), (20, "red")]:
#     pct = (abs_err <= thr).mean() * 100
#     ax.axvline(thr, color=color, linestyle="--", linewidth=1, alpha=0.8)
#     ax.annotate(f"±{thr}: {pct:.1f}%", xy=(thr, pct),
#                 xytext=(thr + 1, pct - 5), fontsize=8, color=color)
# ax.set_title("Cumulative % of Predictions Within ±N AQI")
# ax.set_xlabel("Tolerance (AQI units)")
# ax.set_ylabel("% of predictions")
# ax.set_ylim(0, 105)
# ax.grid(True, alpha=0.3)

# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, "train_error_magnitude.png"), dpi=150, bbox_inches="tight")
# plt.show()

# print("All training performance plots saved.")